include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_declare_return_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    discarded_futures: true
    only_throw_errors: true
    prefer_const_declarations: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_parameters: true
    prefer_foreach: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_pub_dependencies: true
    unawaited_futures: true
    use_if_null_to_convert_nulls_to_bools: true
