name: supershed_worker
description: A new Flutter project.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cv: ^0.2.12
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.6
  flutter_secure_storage: ^8.0.0
  mason_cli: ^0.1.0-dev.50
  pinput: ^2.2.31
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
