name: supershed_worker
description: A new Flutter project.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  binary_stream: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.2
  flutter_spinbox: ^0.13.1
  json: ^0.20.2
  mason_cli: ^0.1.0-dev.50
  mobile_scanner: ^6.0.1
  pinput: ^5.0.0
  shared_preferences: ^2.3.2
  vibration: ^2.0.1
  web_socket_client: ^0.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
